CREATE TABLE LoanType (
    LoanTypeID NUMBER NOT NULL,
    loanName VARCHAR2(50) NOT NULL,
    MaxTerms NUMBER NOT NULL,
    PRIMARY KEY (LoanTypeID)
);

CREATE TABLE Customer (
    FirstName VARCHAR2(30) NOT NULL,
    LastName VARCHAR2(30) NOT NULL,
    SSN CHAR(9) NOT NULL PRIMARY KEY,
    CustAddress VARCHAR2(30) NOT NULL,
    City VARCHAR2(20) NOT NULL,
    CustState CHAR(2) NOT NULL,
    Zip CHAR(5) NOT NULL,
    Phone CHAR(10) NOT NULL,
    PrimaryIncome NUMBER NOT NULL,
    SecondaryIncome NUMBER NOT NULL,
    acctStatus NUMBER(1,0) DEFAULT(0),
    LastUpdate DATE DEFAULT(sysdate)
);

CREATE TABLE JobTitle ( --table works
    PositionName VARCHAR2(30) NOT NULL,
    JobTitleNo CHAR(1) PRIMARY KEY
);

CREATE TABLE Employee ( --table works??? when imput on it's own
    EmployeeNo NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JobTitleNo CHAR(1) REFERENCES JobTitle(JobTitleNo),
    FirstName VARCHAR2(30) NOT NULL,
    LastName VARCHAR2(30) NOT NULL
);

CREATE TABLE Loan (
    LoanNo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    LoanTerm Number NOT NULL,
    AppDate DATE DEFAULT(sysdate),
    LoanAmt NUMBER NOT NULL,
    InterestPercent NUMBER(5,2) NOT NULL,
    MonthlyPayment NUMBER NOT NULL,
    PrincipleBalance NUMBER NOT NULL,
    RemainingPayments NUMBER NOT NULL,
    LoanOfficer NUMBER NOT NULL REFERENCES Employee(EmployeeNo),
    SSN CHAR(9) NOT NULL REFERENCES Customer(SSN),
    LoanTypeID NUMBER NOT NULL REFERENCES LoanType(LoanTypeID),
    w2Received NUMBER(1,0) DEFAULT(0),
    taxReturnAccepted NUMBER(1,0) DEFAULT(0),
    ccReportReceived NUMBER(1,0) DEFAULT(0),
    bankAcctNo VARCHAR2(17) NOT NULL,
    loanUnderwriter NUMBER REFERENCES Employee(EmployeeNo),
    reviewDate DATE,
    checkNo NUMBER,
    bankRouteNo CHAR(9) NOT NULL
);

CREATE TABLE BillingStmt (
    BillingStmtNo NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DueDate DATE DEFAULT(ADD_MONTHS(sysdate, 1)),
    StmtDate DATE DEFAULT(sysdate),
    FinalPmtDate DATE,
    LoanNo NUMBER REFERENCES Loan(LoanNo),
    PaymentAmount NUMBER,
    SSN CHAR(9) REFERENCES Customer(SSN)
);